FROM php:8.2-fpm

# Instala la extensión pdo_pgsql y otras necesarias para Symfony
RUN apt-get update \
    && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

WORKDIR /var/www/html 