<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Restaurante__CLASSMETADATA__' => 0,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Restaurante',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RestauranteRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'nombre' => $o[2],
                        'direccion' => $o[3],
                        'telefono' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'nombre',
                        'direccion' => 'direccion',
                        'telefono' => 'telefono',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'nombre',
                        'direccion' => 'direccion',
                        'telefono' => 'telefono',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'restaurante',
                    ],
                ],
                'idGenerator' => [
                    $o[5],
                ],
                'name' => [
                    'App\\Entity\\Restaurante',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'nombre',
                    'direccion',
                    'telefono',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'direccion',
                    'telefono',
                ],
                'length' => [
                    2 => 255,
                    255,
                    20,
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
