<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250724130957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE restaurante (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, direccion VARCHAR(255) NOT NULL, telefono VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        // Insertar 5 restaurantes de ejemplo
        $this->addSql("INSERT INTO restaurante (nombre, direccion, telefono) VALUES
            ('Restaurante El Buen Sabor', 'Calle Mayor 123, Madrid', '911234567'),
            ('La Parrilla de Juan', 'Avenida del Sol 45, Barcelona', '931112233'),
            ('Pizzería Bella Italia', 'Plaza Central 8, Valencia', '961234567'),
            ('Sushi Sakura', 'Calle Luna 22, Sevilla', '954321987'),
            ('Tapería El Rincón', 'Calle Real 77, Zaragoza', '976112233')
        ");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE restaurante');
    }
}
