<?php

namespace ContainerGLxX2Xs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_RouteArgumentDescriber_MapUploadedFileService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.route_argument_describer.map_uploaded_file' shared service.
     *
     * @return \Nelmio\ApiDocBundle\RouteDescriber\RouteArgumentDescriber\SymfonyMapUploadedFileDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/RouteDescriber/RouteArgumentDescriber/RouteArgumentDescriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/src/RouteDescriber/RouteArgumentDescriber/SymfonyMapUploadedFileDescriber.php';

        return $container->privates['nelmio_api_doc.route_argument_describer.map_uploaded_file'] = new \Nelmio\ApiDocBundle\RouteDescriber\RouteArgumentDescriber\SymfonyMapUploadedFileDescriber();
    }
}
