<?php

namespace ContainerPymiXu7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelProdContainer
{
    /*
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'API de Restaurantes', 'description' => 'Documentación de la API RESTful para gestión de restaurantes.', 'version' => '1.0.0'], 'components' => ['securitySchemes' => ['api_key' => ['type' => 'apiKey', 'in' => 'header', 'name' => 'X-API-KEY']]], 'security' => [['api_key' => []]]]);
    }
}
