<?php

namespace ContainerPymiXu7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_ModelDescribers_ObjectService extends App_KernelProdContainer
{
    /*
     * Gets the private 'nelmio_api_doc.model_describers.object' shared service.
     *
     * @return \Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['nelmio_api_doc.model_describers.object'] = new \Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber(($container->privates['property_info.cache'] ?? $container->load('getPropertyInfo_CacheService')), new \Nelmio\ApiDocBundle\PropertyDescriber\PropertyDescriber(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['nelmio_api_doc.object_model.property_describers.nullable'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\NullablePropertyDescriber());
            yield 1 => ($container->privates['nelmio_api_doc.object_model.property_describers.uuid'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\UuidPropertyDescriber());
            yield 2 => ($container->privates['nelmio_api_doc.object_model.property_describers.translatable'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\TranslatablePropertyDescriber());
            yield 3 => ($container->privates['nelmio_api_doc.object_model.property_describers.array'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\ArrayPropertyDescriber());
            yield 4 => ($container->privates['nelmio_api_doc.object_model.property_describers.dictionary'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\DictionaryPropertyDescriber());
            yield 5 => ($container->privates['nelmio_api_doc.object_model.property_describers.boolean'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\BooleanPropertyDescriber());
            yield 6 => ($container->privates['nelmio_api_doc.object_model.property_describers.float'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\FloatPropertyDescriber());
            yield 7 => ($container->privates['nelmio_api_doc.object_model.property_describers.integer'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\IntegerPropertyDescriber());
            yield 8 => ($container->privates['nelmio_api_doc.object_model.property_describers.string'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\StringPropertyDescriber());
            yield 9 => ($container->privates['nelmio_api_doc.object_model.property_describers.date_time'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\DateTimePropertyDescriber());
            yield 10 => ($container->privates['nelmio_api_doc.object_model.property_describers.object'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\ObjectPropertyDescriber());
            yield 11 => ($container->privates['nelmio_api_doc.object_model.property_describers.compound'] ??= new \Nelmio\ApiDocBundle\PropertyDescriber\CompoundPropertyDescriber());
        }, 12)), ['json'], NULL, false, NULL);
    }
}
