<?php

namespace ContainerPymiXu7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRestauranteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RestauranteRepository' shared autowired service.
     *
     * @return \App\Repository\RestauranteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RestauranteRepository'] = new \App\Repository\RestauranteRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
