<?php

namespace ContainerPymiXu7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_ApiKeyUserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.user.provider.concrete.api_key_user' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\InMemoryUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.user.provider.concrete.api_key_user'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(['api-user' => ['password' => '', 'roles' => ['ROLE_API']]]);
    }
}
