<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGLxX2Xs\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGLxX2Xs/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGLxX2Xs.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGLxX2Xs\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGLxX2Xs\App_KernelTestDebugContainer([
    'container.build_hash' => 'GLxX2Xs',
    'container.build_id' => '09bb5969',
    'container.build_time' => 1753023133,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGLxX2Xs');
