<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_health' => [[], ['_controller' => 'App\\Controller\\HealthController::health'], [], [['text', '/api/health']], [], [], []],
    'app_restaurante_index' => [[], ['_controller' => 'App\\Controller\\RestauranteController::index'], [], [['text', '/api/restaurantes']], [], [], []],
    'app_restaurante_show' => [['id'], ['_controller' => 'App\\Controller\\RestauranteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'app_restaurante_create' => [[], ['_controller' => 'App\\Controller\\RestauranteController::create'], [], [['text', '/api/restaurantes']], [], [], []],
    'app_restaurante_update' => [['id'], ['_controller' => 'App\\Controller\\RestauranteController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'app_restaurante_delete' => [['id'], ['_controller' => 'App\\Controller\\RestauranteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    'App\Controller\HealthController::health' => [[], ['_controller' => 'App\\Controller\\HealthController::health'], [], [['text', '/api/health']], [], [], []],
    'App\Controller\RestauranteController::index' => [[], ['_controller' => 'App\\Controller\\RestauranteController::index'], [], [['text', '/api/restaurantes']], [], [], []],
    'App\Controller\RestauranteController::show' => [['id'], ['_controller' => 'App\\Controller\\RestauranteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'App\Controller\RestauranteController::create' => [[], ['_controller' => 'App\\Controller\\RestauranteController::create'], [], [['text', '/api/restaurantes']], [], [], []],
    'App\Controller\RestauranteController::update' => [['id'], ['_controller' => 'App\\Controller\\RestauranteController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
    'App\Controller\RestauranteController::delete' => [['id'], ['_controller' => 'App\\Controller\\RestauranteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/restaurantes']], [], [], []],
];
