<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgLMWUO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgLMWUO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQgLMWUO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQgLMWUO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQgLMWUO\App_KernelDevDebugContainer([
    'container.build_hash' => 'QgLMWUO',
    'container.build_id' => '57437317',
    'container.build_time' => 1753030321,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgLMWUO');
